baseURL: "https://www.ykzzo.com/"
theme: LoveIt
title: ykzzo's Blog
defaultContentLanguage: zh-cn
languageCode: zh-CN
languageName: 简体中文
hasCJKLanguage: true
paginate: 12
googleAnalytics: ""
copyright: ""
enableRobotsTXT: true
enableEmoji: true
ignoreErrors:
    - error-remote-getjson
    - error-missing-instagram-accesstoken
taxonomies:
  author: "authors"
menu:
    main:
        - weight: 1
          identifier: posts
          pre: ""
          post: ""
          name: 文章
          url: /posts/
          title: ""
        - weight: 2
          identifier: tags
          pre: ""
          post: ""
          name: 标签
          url: /tags/
          title: ""
        - weight: 3
          identifier: categories
          pre: ""
          post: ""
          name: 分类
          url: /categories/
          title: ""
        - weight: 4
          identifier: about
          pre: ""
          post: ""
          name: 关于
          url: /about/
          title: ""
markup:
    highlight:
        codeFences: true
        guessSyntax: true
        lineNos: true
        lineNumbersInTable: true
        noClasses: false
    goldmark:
        extensions:
            definitionList: true
            footnote: true
            linkify: true
            strikethrough: true
            table: true
            taskList: true
            typographer: true
        renderer:
            unsafe: true
    tableOfContents:
        startLevel: 2
        endLevel: 6
params:
    authors:
        name: "YKZZO"
        email: "your_email@example.com"
    busuanzi:
        enable: true
        site_uv: true
        site_uv_pre: <i class="fa fa-user"></i>
        site_uv_post: ""
        site_pv: true
        site_pv_pre: <i class="fa fa-eye"></i>
        site_pv_post: ""
        page_pv: true
        page_pv_pre: <i class="far fa-eye fa-fw"></i>
        page_pv_post: ""
    defaultTheme: light
    fingerprint: sha256
    dateFormat: 2006-01-02
    title: ykzzo的博客
    description: ykzzo的博客
    images:
        - 首页中间的图片
    header:
        desktopMode: normal
        mobileMode: normal
        title:
            logo: ""
            name: ykzzo's Blog
            pre: ""
            post: ""
            typeit: false
    footer:
        enable: true
        custom: ""
        hugo: false
        copyright: true
        author: true
        since: 2022
        icp: ""
        license: <a rel="license external nofollow noopener noreffer"
            href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC
            BY-NC 4.0</a>
    section:
        pagination:
            pagerSize: 20
        dateFormat: 01-02
        rss: 10
        # 显示最近更新文章的数量
        lastUpdatedSize: 10
    list:
        pagination:
            pagerSize: 20
        dateFormat: 01-02
        rss: 10
    app:
        title: ""
        noFavicon: false
        svgFavicon: "20240812085355.svg"
        themeColor: "#ffffff"
        iconColor: "#5bbad5"
        tileColor: "#da532c"
    search:
        enable: true
        type: algolia
        contentLength: 4000
        placeholder: ""
        maxResultLength: 10
        snippetLength: 50
        highlightTag: em
        absoluteURL: false
        algolia:
            index: "ykzzo"
            appID: "FKTW1AAMOA"
            searchKey: "48bbf64c00ada38e233bf8f046654419"
    home:
        rss: 10
        profile:
            enable: true
            gravatarEmail: ""
            avatarURL: "images/20240812085355.jpg"
            title: ""
            subtitle: 欢迎来到我的博客
            typeit: true
            social: true
            disclaimer: ""
        posts:
            enable: true
            paginate: 6
            defaultHiddenFromHomePage: false
    social:
        GitHub: ""
        Linkedin: ""
        Twitter: ""
        Instagram: ""
        Facebook: ""
        Telegram: ""
        Medium: ""
        Gitlab: ""
        Youtubelegacy: ""
        Youtubecustom: ""
        Youtubechannel: ""
        Tumblr: ""
        Quora: ""
        Keybase: ""
        Pinterest: ""
        Reddit: ""
        Codepen: ""
        FreeCodeCamp: ""
        Bitbucket: ""
        Stackoverflow: ""
        Weibo: ""
        Odnoklassniki: ""
        VK: ""
        Flickr: ""
        Xing: ""
        Snapchat: ""
        Soundcloud: ""
        Spotify: ""
        Bandcamp: ""
        Paypal: ""
        Fivehundredpx: ""
        Mix: ""
        Goodreads: ""
        Lastfm: ""
        Foursquare: ""
        Hackernews: ""
        Kickstarter: ""
        Patreon: ""
        Steam: ""
        Twitch: ""
        Strava: ""
        Skype: ""
        Whatsapp: ""
        Zhihu: ""
        Douban: ""
        Angellist: ""
        Slidershare: ""
        Jsfiddle: ""
        Deviantart: ""
        Behance: ""
        Dribbble: ""
        Wordpress: ""
        Vine: ""
        Googlescholar: ""
        Researchgate: ""
        Mastodon: ""
        Thingiverse: ""
        Devto: ""
        Gitea: ""
        XMPP: ""
        Matrix: ""
        Bilibili: ""
        Discord: ""
        DiscordInvite: ""
        Lichess: ""
        ORCID: ""
        Pleroma: ""
        Kaggle: ""
        MediaWiki: ""
        Plume: ""
        HackTheBox: ""
        RootMe: ""
        Phone: ""
        Email: ""
        RSS: true
    page:
        hiddenFromHomePage: false
        hiddenFromSearch: false
        twemoji: false
        lightgallery: true
        ruby: true
        fraction: true
        fontawesome: true
        linkToMarkdown: false
        rssFullText: false
        toc:
            enable: true
            keepStatic: false
            auto: true
        code:
            copy: true
            maxShownLines: 50
        math:
            enable: true
            inlineLeftDelimiter: ""
            inlineRightDelimiter: ""
            blockLeftDelimiter: ""
            blockRightDelimiter: ""
            copyTex: true
            mhchem: true
        mapbox:
            accessToken: ""
            lightStyle: mapbox://styles/mapbox/light-v10?optimize=true
            darkStyle: mapbox://styles/mapbox/dark-v10?optimize=true
            navigation: true
            geolocate: true
            scale: true
            fullscreen: true
        share:
            enable: true
            Twitter: true
            Facebook: true
            Linkedin: true
            Whatsapp: false
            Pinterest: false
            Tumblr: false
            HackerNews: false
            Reddit: false
            VK: false
            Buffer: false
            Xing: false
            Line: true
            Instapaper: false
            Pocket: false
            Flipboard: false
            Weibo: true
            Blogger: false
            Baidu: false
            Odnoklassniki: false
            Evernote: false
            Skype: false
            Trello: false
            Mix: false
        comment:
            enable: true
            disqus:
                enable: false
                shortname: ""
            gitalk:
                enable: false
                owner: ""
                repo: ""
                clientId: ""
                clientSecret: ""
            valine:
                enable: false
                appId: ""
                appKey: ""
                placeholder: ""
                avatar: mp
                meta: ""
                pageSize: 10
                lang: ""
                visitor: true
                recordIP: true
                highlight: true
                enableQQ: false
                serverURLs: ""
                emoji: ""
            facebook:
                enable: false
                width: 100%
                numPosts: 10
                appId: ""
                languageCode: zh_CN
            telegram:
                enable: false
                siteID: ""
                limit: 5
                height: ""
                color: ""
                colorful: true
                dislikes: false
                outlined: false
            commento:
                enable: false
            utterances:
                enable: false
                repo: ""
                issueTerm: pathname
                label: ""
                lightTheme: github-light
                darkTheme: github-dark
            giscus:
                enable: true
                repo: "1262706090/Giscus"
                repoId: "R_kgDOMiVsFQ"
                category: "Announcements"
                categoryId: "DIC_kwDOMiVsFc4ChjcH"
                lang: ""
                mapping: "pathname"
                reactionsEnabled: "1"
                emitMetadata: "0"
                inputPosition: bottom
                lazyLoading: false
                lightTheme: light
                darkTheme: dark
        library:
            css: {}
            js: {}
        seo:
            images: []
            publisher:
                name: ""
                logoUrl: ""
    typeit:
        speed: 100
        cursorSpeed: 1000
        cursorChar: "|"
        duration: -1
    verification:
        google: ""
        bing: ""
        yandex: ""
        pinterest: ""
        baidu: "codeva-rd9ZCXPdEK"
    seo:
        image: ""
        thumbnailUrl: ""
    analytics:
        enable: true
        google:
            id: ""
            anonymizeIP: true
        baidu:
            id: ""
    cdn:
        data: ""
    compatibility:
        polyfill: false
        objectFit: false
    # Display a message at the beginning of an article to warn the readers that it's content may be outdated.
    # 在文章末尾显示提示信息，提醒读者文章内容可能过时。
    outdatedInfoWarning:
        enable: true
        hint: 90
        warn: 180
sitemap:
    changefreq: weekly
    filename: sitemap.xml
    priority: 0.5
Permalinks:
    posts: :filename
privacy:
    googleAnalytics: {}
    twitter:
        enableDNT: true
    youtube:
        privacyEnhanced: true
mediaTypes:
    text/plain:
        suffixes:
            - md
outputFormats:
    MarkDown:
        mediaType: text/plain
        isPlainText: true
        isHTML: false
outputs:
    home:
        - HTML
        - RSS
        - JSON
    page:
        - HTML
        - MarkDown
    section:
        - HTML
        - RSS
    taxonomy:
        - HTML
        - RSS
    taxonomy:
        - HTML

