name: HugoDeploy

on:
    push: # 当有 push 事件时运行下面的 jobs
    workflow_dispatch: # 手动触发工作流
    # schedule:
    #     # 每天早上8:00运行
    #     - cron: "0 0 * * *"

env:
    TZ: Asia/Shanghai # 设置当前环境时区

jobs:
    deploy: # 任务名自取
        runs-on: ubuntu-latest # 在什么环境运行任务
        steps:
            - name: Checkout
              uses: actions/checkout@v2 # 使用 actions/checkout 这个 action
              with:
                  submodules: true # 获取 submodule 主题
                  fetch-depth: 0 # 获取所有历史记录

            - name: Disable quotePath
              run: git config --global core.quotePath false

            - name: Setup Hugo
              uses: peaceiris/actions-hugo@v2 # Hugo 官方提供的 action
              with:
                  hugo-version: "latest" # 获取最新版本的 Hugo
                  extended: true # 获取 extended 版本，支持 SCSS 等高级功能

            - name: Cache resources
              uses: actions/cache@v3 # 缓存 resources 文件夹以加快生成速度
              with:
                  path: resources
                  key: ${{ runner.os }}-hugocache-${{ hashFiles('content/**/*') }}
                  restore-keys: ${{ runner.os }}-hugocache-

            - name: Build
              run: hugo --minify # 使用 Hugo 构建静态网页并最小化输出

            - name: Create CNAME file # 创建 CNAME 文件
              uses: finnp/create-file-action@master
              with:
                  filename: "./public/CNAME"
                  content: "ykzzo.com"

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3 # 自动发布 GitHub Pages 的 action
              with:
                  # 使用 personal access token 发布到外部仓库
                  external_repository: 1262706090/1262706090.github.io # 发布到指定仓库
                  personal_token: ${{ secrets.PERSONAL_TOKEN }} # GitHub Secrets 中配置的 personal access token
                  publish_dir: ./public # 发布 public 文件夹中的内容
                  publish_branch: main # 发布到 main 分支
